### ISSUE TITLE
I am getting errors when I try ionic serve

### ISSUE THREAD

**Issue by lallen30** [ionicthemes/ionic5-starter-app#10]
Please help. I purchased the Ionic4 full starter app. I have followed the directions in documentation.

I am getting the following error log when I try npm install
[2020-03-04T14_17_24_340Z-debug.log](https://github.com/ionicthemes/ionic4-full-starter-app/files/4287795/2020-03-04T14_17_24_340Z-debug.log)

and the following error when I try ionic serve
`[ng]
[ng] ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (79)
[ng] For more information on which environments are supported please see:
[ng] https://github.com/sass/node-sass/releases/tag/v4.12.0
[ng]     at module.exports (/Users/larryallen/ionic/knoxweb/ionic4-full-starter-app-pro-version/node_modules/node-sass/lib/binding.js:13:13)
[ng]     at Object.<anonymous> (/Users/larryallen/ionic/knoxweb/ionic4-full-starter-app-pro-version/node_modules/node-sass/lib/index.js:14:35)
[ng]     at Module._compile (internal/modules/cjs/loader.js:1151:30)
[ng]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
[ng]     at Module.load (internal/modules/cjs/loader.js:1000:32)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
[ng]     at Module.require (internal/modules/cjs/loader.js:1040:19)
[ng]     at require (internal/modules/cjs/helpers.js:72:18)
[ng]     at Object.sassLoader (/Users/larryallen/ionic/knoxweb/ionic4-full-starter-app-pro-version/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in ./src/theme/variables.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (79)
[ng] For more information on which environments are supported please see:
[ng] https://github.com/sass/node-sass/releases/tag/v4.12.0
[ng]     at module.exports (/Users/larryallen/ionic/knoxweb/ionic4-full-starter-app-pro-version/node_modules/node-sass/lib/binding.js:13:13)
[ng]     at Object.<anonymous> (/Users/larryallen/ionic/knoxweb/ionic4-full-starter-app-pro-version/node_modules/node-sass/lib/index.js:14:35)
[ng]     at Module._compile (internal/modules/cjs/loader.js:1151:30)
[ng]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
[ng]     at Module.load (internal/modules/cjs/loader.js:1000:32)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
[ng]     at Module.require (internal/modules/cjs/loader.js:1040:19)
[ng]     at require (internal/modules/cjs/helpers.js:72:18)
[ng]     at Object.sassLoader (/Users/larryallen/ionic/knoxweb/ionic4-full-starter-app-pro-version/node_modules/sass-loader/lib/loader.js:46:72)
[ng] ERROR in node_modules/@angular/fire/firebase.app.module.d.ts(2,74): error TS2307: Cannot find module 'firebase/app'.
[ng] node_modules/@angular/fire/firestore/collection-group/collection-group.d.ts(2,27): error TS2307: Cannot find module 'firebase/app'.
[ng] node_modules/@angular/fire/firestore/collection/collection.d.ts(2,27): error TS2307: Cannot find module 'firebase/app'.
[ng] node_modules/@angular/fire/firestore/document/document.d.ts(5,27): error TS2307: Cannot find module 'firebase/app'.
[ng] node_modules/@angular/fire/firestore/firestore.d.ts(8,27): error TS2307: Cannot find module 'firebase/app'.
[ng] node_modules/@angular/fire/firestore/interfaces.d.ts(2,27): error TS2307: Cannot find module 'firebase/app'.
[ng] src/app/firebase/firebase-integration.service.ts(220,30): error TS2339: Property 'id' does not exist on type 'DocumentSnapshot<FirebaseSkillModel>'.
[ng]   Property 'id' does not exist on type 'DocumentSnapshotDoesNotExist'.
[ng] src/app/firebase/firebase-integration.service.ts(234,30): error TS2339: Property 'id' does not exist on type 'DocumentSnapshot<FirebaseUserModel>'.
[ng]   Property 'id' does not exist on type 'DocumentSnapshotDoesNotExist'.
[ng]
[ng] ℹ ｢wdm｣: Failed to compile.`

**Comment by djabif** [comment]
Hi, are you using the [latest version](https://ionic-5-full-starter-app-docs.ionicthemes.com/changelog#2-0-0-2020-02-14-basic-and-pro-versions) of the template with Ionic 5?

**Comment by djabif** [comment]
Hey, are you still getting trouble with this issue?
