### ISSUE TITLE
Error running the template in Xcode

### ISSUE THREAD

**Issue by jalonsoad** [ionicthemes/ionic5-starter-app#11]
Hi there,
Im getting this error when trying to run the template on Xcode:
I'm using the ionic5 Version 2.0.0 fo the theme.
NSForwarding: warning: object 0x1cf790148 of class 'PFEmbeddedMulticasterImplementation' does not implement doesNotRecognizeSelector: -- abort
The function who is crashing is:

func registerPlugins() {
    var numClasses = UInt32(0);
    let classes = objc_copyClassList(&numClasses)
    for i in 0..<Int(numClasses) {
      **let c: AnyClass = classes!<<<< HERE IS THE ERROR!!!**
      if class_conformsToProtocol(c, CAPBridgedPlugin.self) {
        let pluginClassName = NSStringFromClass(c)
        let pluginType = c as! CAPPlugin.Type
        let bridgeType = c as! CAPBridgedPlugin.Type
        
        registerPlugin(pluginClassName, bridgeType.jsName(), pluginType)
      }
    }
  }
Any ideas?

**Comment by djabif** [comment]
Hi, can you please give us more details to reproduce this error?

**Comment by djabif** [comment]
Hey are you still getting trouble with this?
