### ISSUE TITLE
ionic 5 

### ISSUE THREAD

**Issue by hadyhinnanwi** [ionicthemes/ionic5-starter-app#12]
Hello guys , i wanna ask you 
i just bought  ionic 5 universal template  any idea how can i use the template in xcode 11 ..

cheers

**Comment by djabif** [comment]
Hi, the template works fine in xcode11. 
Which issue are you experiencing?

**Comment by hadyhinnanwi** [comment]
Thank you for your response i want to know how can i add it to xcode im new
to this and its my 1st template online

**Comment by djabif** [comment]
Check https://capacitor.ionicframework.com/docs/ios

**Comment by djabif** [comment]
Please let me know if you need further assistance or if I can close the issue.

**Comment by hadyhinnanwi** [comment]
Hello , sorry for late reply to be honest I’m still confused  I thought it would be easy to install but its seems more complicated ..
I will search more on google thank you so much

**Comment by djabif** [comment]
Don't worry, I can guide you. 
Are you using [Ionic 5 Full Starter App - PRO](https://ionicthemes.com/product/ionic5-full-starter-app-pro-version)?
Do you plan to work with [Capacitor](https://capacitor.ionicframework.com/)?

**Comment by djabif** [comment]
Closed due to inactivity.
