### ISSUE TITLE
image cropped when change aspect ratio

### ISSUE THREAD

**Issue by alkahtani** [ionicthemes/ionic5-starter-app#16]
I got an image and when i change the aspect ratio 10:4 the image getting cropped 
<img width="304" alt="Screen Shot 2020-06-06 at 6 16 20 PM" src="https://user-images.githubusercontent.com/13502824/83947856-39c83d00-a822-11ea-9f33-a5412ce325c5.png">

`<ion-row class="image-row">
    <ion-col size="12">
      <app-image-shell [display]="'cover'" animation="spinner" class="" [src]="details?.image">
        <app-aspect-ratio [ratio]="{w:10, h:6}">
        </app-aspect-ratio>
      </app-image-shell>
    </ion-col>
  </ion-row>`

the original image 
![cat1-f1](https://user-images.githubusercontent.com/13502824/83947889-7005bc80-a822-11ea-9930-ba17262527c6.jpg)

**Comment by djabif** [comment]
If you change the ratio of the image, it will get cropped or stretched... you can learn more about the image shell components in https://pro-ion4fullpwa.firebaseapp.com/showcase/app-shell/image-shell

**Comment by alkahtani** [comment]
@djabif  sorry for being late to reply , it is clear now , you can close this issue.
