### ISSUE TITLE
Impossible to navigate when launching app

### ISSUE THREAD

**Issue by hbek999** [ionicthemes/ionic5-starter-app#17]
Hello,

I have just installed the app and I launched it using ionic serve.
After that the app is opened in http://localhost:8100/walkthrough
The page is displayed but impossible to navigate.

Could anybody help ?
Thank you
![ionic5app](https://user-images.githubusercontent.com/29752162/85920026-8aa2e280-b870-11ea-9937-daec9b137292.jpg)

**Comment by djabif** [comment]
Hi @hbek999, you need to browse the project as a mobile app. To do this, you need to open your browser's inspector and then toggle the device mode. To do this just right click on your browser and click Inspect. [Check this guide to learn how to do it in Chrome. ](https://developers.google.com/web/tools/chrome-devtools/device-mode/)

**Comment by hbek999** [comment]
Hi @djabif, Thank you very much. It works ! :-)
