### ISSUE TITLE
html in app-text-shell

### ISSUE THREAD

**Issue by liquidcms** [ionicthemes/ionic5-starter-app#18]
Is there a way to have app-ext-shell handle HTML (i.e. innerHTML)?

**Comment by djabif** [comment]
Hi, the bouncing effect of the text shell works by applying a CSS background animation to the element containing the text.
In theory, you can apply this CSS animation to any HTML element as it is pure CSS.

**Comment by liquidcms** [comment]
Is it possible to have your sidemenu logo display logo as transparent (or at least set background colour. I don’t think I have done much to your original except to set autohide so that clicking it will close the menu.

 

<ion-toolbar>
  <ion-row class="user-details-wrapper">
    <ion-col size="4">
      <ion-menu-toggle auto-hide="true">
        <ion-item >
          <app-aspect-ratio [ratio]="{w: 1, h: 1}">
            <app-image-shell animation="spinner" [src]="'./assets/custom-icons/ionic.png'"></app-image-shell>
          </app-aspect-ratio>
        </ion-item>
      </ion-menu-toggle>
    </ion-col>
    <ion-col class="user-info-wrapper" size="8">
      <h3 class="user-name">Ionic 5</h3>
      <h5 class="user-handle">@withAngular9</h5>
    </ion-col>
  </ion-row>
</ion-toolbar>

 

And the image I am using is a transparent PNG, yet it shows like this: https://monosnap.com/file/PbyeN8WCDxyzLJPzqne2bb4Zzgq88z 

 

Peter Lindstrom

LiquidCMS - Content Solution Experts

Voice: +1 613.612.1419

Skype: liquidcms

Email:  peter@LiquidCMS.ca

Web:     <http://www.liquidcms.ca/> www.LiquidCMS.ca

**Comment by djabif** [comment]
@liquidcms answered your last question in a new issue because it was not related to this one.
