### ISSUE TITLE
Can starter app be built?

### ISSUE THREAD

**Issue by liquidcms** [ionicthemes/ionic5-starter-app#22]
I have unzipped your starter app. 

npm install -> runs fine
ionic serve -> app runs in browser

ionic info
Ionic:
   Ionic CLI                     : 6.10.1 (C:\Users\Peter\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:
   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.1.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:
   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.2.8

System:
   Android SDK Tools : 26.1.1 (c:\android-sdk)
   NodeJS            : v12.18.2 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.5
   OS                : Windows 7

but running "ionic cordova build android"

gives:

Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "android" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Peter\AppData\Roaming\npm-cache\_logs\2020-07-27T20_36_00_886Z-debug.log
    at ChildProcess.whenDone (C:\Users\Peter\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\su
perspawn.js:135:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\Peter\AppData\Roaming\npm\node_modules\cordova\node_modules\cross-spawn\lib\enoent
.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  stderr: 'npm ERR! code ENOLOCAL\n' +
    'npm ERR! Could not install from "android" as it does not contain a package.json file.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\Peter\\AppData\\Roaming\\npm-cache\\_logs\\2020-07-27T20_36_00_886Z-debug.log\n',
  code: 1

It also seems odd that your folder structure includes android and io folders in the root folder; typically these would be under platforms.

**Comment by liquidcms** [comment]
using --verbose i see:

  ionic:lib:integrations:cordova:config Invalid package.json for Cordova. Missing or invalid Cordova entries in 'E:\\www
\\ionic5-starter\\package.json' +18ms

possibly this is the issue?

**Comment by djabif** [comment]
The project uses [Capacitor](https://capacitorjs.com/docs) so iOS and Android folders are part of the app. 
Please [follow the documentation](https://ionic-5-full-starter-app-docs.ionicthemes.com/capacitor) to see how to run this app with Capacitor.

**Comment by djabif** [comment]
@liquidcms can I close this issue?

**Comment by liquidcms** [comment]
Please close. I was able to build using android studio. 
--
Peter Lindstrom
LiquidCMS Wednesday, 05 August 2020, 08:05a.m. -04:00 from Dayana Jabif  notifications@github.com :
