### ISSUE TITLE
ionic5-full-starter-app-pro-version-2.2.0 ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by strogof** [ionicthemes/ionic5-starter-app#23]
hi
I only removed capacitor following your guide at
https://ionic-5-full-starter-app-docs.ionicthemes.com/capacitor#how-to-remove-capacitor-and-use-cordova
and tried to run the app on an android 7.0 device
this is the result
suggestion?

![Screenshot_20201015-142439](https://user-images.githubusercontent.com/12082024/96123527-3db44c00-0ef3-11eb-90fc-4a13518223b3.png)

**Comment by djabif** [comment]
Hi, are you using the template basic or pro version ?

**Comment by strogof** [comment]
hi, ionic5-full-starter-app-pro-version-2.2.0

**Comment by djabif** [comment]
Did you remove all the references to Capacitor?
Also from the Maps and Video Playlist?
Are you getting any other error message?

**Comment by djabif** [comment]
I just tried following the [guide](https://ionic-5-full-starter-app-docs.ionicthemes.com/capacitor#how-to-remove-capacitor-and-use-cordova) and also had to remove references to Capacitor from Maps and Video Playlist.

Then used ` ionic cordova prepare android` and `ionic cordova run android -l` and the app worked fine in the android emulator.

**Comment by strogof** [comment]
************************************
error log android studio
************************************
2020-10-18 09:59:13.551 15203-15292/io.ionic.starter E/WebViewAssetServer: Unable to open index.html
    java.io.FileNotFoundException: www/index.html
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:682)
        at com.ionicframework.cordova.webview.AndroidProtocolHandler.openAsset(AndroidProtocolHandler.java:30)
        at com.ionicframework.cordova.webview.WebViewLocalServer.handleLocalRequest(WebViewLocalServer.java:282)
        at com.ionicframework.cordova.webview.WebViewLocalServer.shouldInterceptRequest(WebViewLocalServer.java:228)
        at com.ionicframework.cordova.webview.IonicWebViewEngine$ServerClient.shouldInterceptRequest(IonicWebViewEngine.java:140)
        at ks0.a(chromium-Monochrome.aab-stable-424009923:16)
        at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-Monochrome.aab-stable-424009923:2)

********************
maps.page.ts
********************
`import { Component, ViewChild, AfterViewInit } from '@angular/core';
import { LoadingController } from '@ionic/angular';

// import { Plugins } from '@capacitor/core';
// const { Geolocation } = Plugins;

import { GoogleMapComponent } from '../components/google-map/google-map.component';

@Component({
  selector: 'app-maps',
  templateUrl: './maps.page.html',
  styleUrls: [
    './styles/maps.page.scss'
  ]
})
export class MapsPage implements AfterViewInit {

  @ViewChild(GoogleMapComponent, { static: false }) _GoogleMap: GoogleMapComponent;
  map: google.maps.Map;
  mapOptions: google.maps.MapOptions = {
    zoom: 15,
    center: {lat: -34.9199842, lng: -56.149849}
    // uncomment the following line if you want to remove the default Map controls
    // disableDefaultUI: true
  };
  loadingElement: any;

  constructor(private loadingController: LoadingController) { }

  ngAfterViewInit() {
    // GoogleMapComponent should be available
    this._GoogleMap.$mapReady.subscribe(map => {
      this.map = map;
      console.log('ngAfterViewInit - Google map ready');
    });
    this.createLoader();
  }

  async createLoader() {
    this.loadingElement = await this.loadingController.create({
      message: 'Trying to get your current location...'
    });
  }

  async presentLoader() {
    await this.loadingElement.present();
  }

  async dismissLoader() {
    if (this.loadingElement) {
      await this.loadingElement.dismiss();
    }
  }

  public geolocateMe(): void {
    // this.presentLoader();
    // Geolocation.getCurrentPosition().then(position => {

    //   const current_location = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
    //   this.map.panTo(current_location);

    //   // add a marker
    //   const marker = new google.maps.Marker({
    //     position: current_location,
    //     title: 'You are here!',
    //     // animation: google.maps.Animation.DROP
    //   });

    //   // To add the marker to the map, call setMap();
    //   marker.setMap(this.map);

    // }).catch((error) => {
    //   console.log('Error getting current location', error);

    // }).finally(() => this.dismissLoader());
  }
}
`
**************************
video-playlist.page.ts
**************************
`import { Component, OnInit, HostBinding, Inject, PLATFORM_ID } from '@angular/core';
import { VideoPlaylistModel } from './video-playlist.model';
import { VgApiService } from '@videogular/ngx-videogular/core';
import { ActivatedRoute } from '@angular/router';
// import { Plugins } from '@capacitor/core';
import { switchMap } from 'rxjs/operators';
import { isPlatformBrowser } from '@angular/common';
// const { Share } = Plugins;

@Component({
  selector: 'app-video-playlist',
  templateUrl: './video-playlist.page.html',
  styleUrls: [
    './styles/video-playlist.page.scss',
    './styles/video-playlist.shell.scss'
  ]
})
export class VideoPlaylistPage implements OnInit {
  ssr = true;
  start_playing = false;
  api: VgApiService;
  video_playlist_model: VideoPlaylistModel;

  @HostBinding('class.is-shell') get isShell() {
    return (this.video_playlist_model && this.video_playlist_model.isShell) ? true : false;
  }

  constructor(
    private route: ActivatedRoute,
    @Inject(PLATFORM_ID) private platformId: object
  ) { }

  ngOnInit(): void {
    // In SSR show a placeholder for the <vg-player>
    if (isPlatformBrowser(this.platformId)) {
      this.ssr = false;
    }

    this.route.data
    .pipe(
      // Extract data for this page
      switchMap((resolvedRouteData) => resolvedRouteData['data'].state)
    )
    .subscribe((state: any) => {
      this.video_playlist_model = state;
      if (!state.isShell) {
        this.video_playlist_model.video_playlist = state.videos;
        this.video_playlist_model.selected_video = state.videos[0];
      }
    }, (error) => console.log(error));
  }

  playMedia(media) {
    // Check if this media is not the same we are currently playing
    if (media !== this.video_playlist_model.selected_video) {
      // Change sources
      this.video_playlist_model.selected_video = media;
      // When changing sources we wait until the metadata is loaded and then we start playing the video
    }
  }

  onPlayerReady(api: VgApiService) {
    this.api = api;
    this.api.getDefaultMedia().subscriptions.loadedMetadata.subscribe(this.playVideo.bind(this));
  }

  playVideo() {
    if (this.start_playing) {
      this.api.play();
    } else {
      this.start_playing = true;
    }
  }

  shareMedia() {
    // const selectedVideo = this.video_playlist_model.selected_video;
    // Share.share({
    //   title: selectedVideo.title,
    //   text: selectedVideo.description,
    //   url: 'https://ionicthemes.com/',
    //   dialogTitle: 'Share Media'
    // })
    // .then(() => console.log('Successful share'))
    // .catch((error) => console.log('Error sharing', error));
  }
}
`

**Comment by strogof** [comment]
hi,
can you help me, please
I'm stuck

**Comment by strogof** [comment]
hi,
"ionic cordova run android -l" works fine
the problem remains with vsCode debug
if I try to attach to running process 
started with the problem remains with "ionic cordova run android -l "
this is what I see in debug console

Could not load source map from 19.js.map
Could not load source map from 10.js.map
Could not load source map from 34.js.map
Could not load source map from 17.js.map
Could not load source map from 4.js.map
Could not load source map from 15.js.map
Could not load source map from 5.js.map
Could not load source map from 6.js.map
Could not load source map from 28.js.map
Could not load source map from tap-click-252af35a-js.js.map
Could not load source map from status-tap-0b3e89c4-js.js.map
Could not load source map from keyboard-dd970efc-js.js.map
Could not load source map from focus-visible-15ada7f7-js.js.map
Could not load source map from swipe-back-0a6a44c8-js.js.map

**********************************************
this is my launch.json
**********************************************
{
    // Usare IntelliSense per informazioni sui possibili attributi.
    // Al passaggio del mouse vengono visualizzate le descrizioni degli attributi esistenti.
    // Per altre informazioni, visitare: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Attach to running Android on device",
            "type": "cordova",
            "request": "attach",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },

        {
            "name": "Run Android on device",
            "type": "cordova",
            "request": "launch",
            "platform": "android",
            "target": "device",
            "port": 9222,
            "sourceMaps": true,
            "cwd": "${workspaceFolder}"
        },
    ]
}

**Comment by djabif** [comment]
If `ionic cordova run android -l` works fine then, I'm afraid your issue seems to be related to VScode and not particularly to the template.

Is there anything else I can do for you?

**Comment by strogof** [comment]
thanks for your time

**Comment by sachinsc** [comment]
just www folder delete and delete android folder from the platform then rebuild android platform
