### ISSUE TITLE
pwa does not work

### ISSUE THREAD

**Issue by strogof** [ionicthemes/ionic5-starter-app#25]
hi,
the PWA build of my app (see issue 24) does not work

steps to create pwa

ng add @angular/pwa
ionic build --prod
copy of dist/app/browser folder content in to public/myapp folder of my nodejs/express  https server web

a blank page appears when I visit the page myServeNode/myApp/index.html

this is what I see in console

runtime.e695f16045af90ade33d.js:1 Uncaught SyntaxError: Unexpected token '<'
polyfills.e31f4765ecd723ca5c11.js:1 Uncaught SyntaxError: Unexpected token '<'
main.4c98ab9e5cf50807b935.js:1 Uncaught SyntaxError: Unexpected token '<'

**Comment by djabif** [comment]
Hi, what's the reason behind doing this?

> copy of dist/app/browser folder content in to public/myapp folder of my nodejs/express https server web

**Comment by strogof** [comment]
hi, 
deploy the PWA to my web server

**Comment by djabif** [comment]
Sorry, but it's hard for me to help you without seeing your code. 
Are you testing this with a fresh copy of the template or did you modify the code?

You can follow [this guide](https://ionicthemes.com/tutorials/about/the-complete-guide-to-progressive-web-apps-with-ionic4#building-a-progressive-web-app-with-ionic4) to see how to build and deploy a PWA with ionic and angular.

**Comment by strogof** [comment]
it seems your template work fine only with capacitor which is not production ready IMHO
my cordova app works only on android (after several problems see issue 23)
but in ios and pwa is a mess
I followed your guide but the backend server for my app is node/express

**Comment by strogof** [comment]
I tried again following the guide

PS D:\progetti\shoppyNetNew> ng add @angular/pwa
Installed packages for tooling via npm.
CREATE ngsw-config.json (624 bytes)
CREATE src/manifest.webmanifest (1330 bytes)
CREATE src/assets/icons/icon-128x128.png (1253 bytes)
CREATE src/assets/icons/icon-144x144.png (1394 bytes)
CREATE src/assets/icons/icon-152x152.png (1427 bytes)
CREATE src/assets/icons/icon-192x192.png (1790 bytes)
CREATE src/assets/icons/icon-384x384.png (3557 bytes)
CREATE src/assets/icons/icon-512x512.png (5008 bytes)
CREATE src/assets/icons/icon-72x72.png (792 bytes)
CREATE src/assets/icons/icon-96x96.png (958 bytes)
UPDATE angular.json (6439 bytes)
UPDATE src/index.html (6821 bytes)
√ Packages installed successfully.
PS D:\progetti\shoppyNetNew> http-server ./www -p 8888
Starting up http-server, serving ./www
Available on:
  http://192.168.1.239:8888
  http://127.0.0.1:8888
Hit CTRL-C to stop the server
[2020-11-17T18:54:34.876Z]  "GET /" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Mobile Safari/537.36 Chrome-Lighthouse"
(node:21308) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated[2020-11-17T18:54:34.946Z]  "GET /favicon.ico" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Mobile Safari/537.36 Chrome-Lighthouse"
[2020-11-17T18:54:34.948Z]  "GET /favicon.ico" Error (404): "Not found"
[2020-11-17T18:54:36.332Z]  "GET /robots.txt" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 
Mobile Safari/537.36 Chrome-Lighthouse"
[2020-11-17T18:54:36.334Z]  "GET /robots.txt" Error (404): "Not found"
[2020-11-17T18:54:36.494Z]  "GET /asset-manifest.json" "Mozilla/5.0 (Linux; Android 7.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.7 Mobile Safari/537.36 Chrome-Lighthouse"
[2020-11-17T18:54:36.496Z]  "GET /asset-manifest.json" Error (404): "Not found"
>

lighthouse http://localhost:8888 --view

![image](https://user-images.githubusercontent.com/12082024/99434888-a5552100-290f-11eb-9b87-8d0110d89578.png)

**Comment by djabif** [comment]
Answer provided in https://github.com/ionicthemes/ionic5-starter-app/issues/26#issuecomment-730677521

**Comment by strogof** [comment]
I don't think it can be closed.
even though I have given up on your support
the bug reported is always there.
provided that one day you decide to check ...
