### ISSUE TITLE
template buggy and support near to zero 

### ISSUE THREAD

**Issue by strogof** [ionicthemes/ionic5-starter-app#26]
to know my problems with the template see the issues 23,24 and 25

the level of support:

**### issue 23 subject**:
ionic5-full-starter-app-pro-version-2.2.0 ERR_CONNECTION_REFUSED

### **support answer**
Hi, are you using the template basic or pro version?

### **issue 24**
opened with error log, steps followed and ionic info in the body

### **first answer support answer**
Are you using Cordova instead of Capacitor?

### **second reply six days later**
Can you please send me your error log and what steps are you following to build and deploy your iOS app?

**Comment by djabif** [comment]
Hello Luigi, I'm sorry to read that you are not satisfied with the support provided. 

From the description of your issues it's impossible for me to understand what could be happening in your development environment and on your node/express server. 
Please take in consideration that there's another human from the other side trying to help.

Do you have the files `manifest.webmanifest` and `ngsw-config.json`?

Can I ask you to try to use Firebase to host your app, just as a test to see if it works? 
Please follow this [guide](https://ionicframework.com/docs/angular/pwa).

As stated in our [terms and conditions](https://ionicthemes.com/terms), we don't offer support for installation, customization, administration of the templates. We do, however offer support for errors and bugs pertaining to the templates. We are also happy to walk customers through the template structure and answer any support queries in that regard.

If you are not satisfied with the template I can offer to give you a refund. 
We want our customers to love the template.

**Comment by strogof** [comment]
hi Dayana,
I don't need a refund, but help and this is not happening, 
I suspect you don't even read my posts, as you ask me for things I have already provided you

have you tried to reproduce my problem with ios or pwa? no.

if I remove capacitor from the original template and try to deploy the pwa 
as described in the guide you suggested, 
the result is what I sent you in the lighthouse report. 
this is a bug it is not installation support

if I remove capacitor from the original template and try to compile in ios environment 
as you suggested (ionic cordova prepare ios and then try to run on Xcode),
the result is the one described in issue 24. 
this is a bug it is not installation support

in the meantime, after 10 days from the publication on the play store, I can't get my app on the apple store

anyway, yes, I have the files manifest.webmanifest and ngsw-config.json and
 I'll try to deploy to firebase and let you now...

**Comment by strogof** [comment]
hi,
 I tried to to use Firebase to host my app, but something is wrong..
what did I do wrong/missing? 

### **firebase deploy**

=== Deploying to 'teststarter-d0347'...

i  deploying hosting
i  hosting[teststarter-d0347]: beginning deploy...
i  hosting[teststarter-d0347]: found 1 files in www
+  hosting[teststarter-d0347]: file upload complete
i  hosting[teststarter-d0347]: finalizing version...
i  hosting[teststarter-d0347]: releasing new version...
+  hosting[teststarter-d0347]: release complete

+  Deploy complete!

Project Console: https://console.firebase.google.com/project/teststarter-d0347/overview
Hosting URL: https://teststarter-d0347.web.app
PS D:\progetti\shoppyNetNew> firebase emulators:start
i  emulators: Starting emulators: hosting
i  hosting: Serving hosting files from: www
+  hosting: Local server: http://localhost:5000

┌──────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your apps. │
└──────────────────────────────────────────────────────────────┘

┌──────────┬────────────────┐
│ Emulator │ Host:Port      │
├──────────┼────────────────┤
│ Hosting  │ localhost:5000 │
└──────────┴────────────────┘
  Other reserved ports: 4400


### **firebase console**
![image](https://user-images.githubusercontent.com/12082024/99814143-dd937400-2b48-11eb-9f0f-7beb07842786.png)

### **https://teststarter-d0347.firebaseapp.com/**
![image](https://user-images.githubusercontent.com/12082024/99814292-16334d80-2b49-11eb-933d-4e51ce11c41a.png)

### **https://teststarter.firebaseapp.com/**
![image](https://user-images.githubusercontent.com/12082024/99815383-8098bd80-2b4a-11eb-9b13-a3e580c919d4.png)

**Comment by djabif** [comment]
Can I see your `firebase.json` file?

Make sure your configuration looks like this:

{
  "hosting": {
    "public": "dist/app/browser",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [ {
      "source": "**",
      "destination": "/index.html"
    } ],
    "headers": [
      {
        "source": "**",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache, no-store, must-revalidate"
          }
        ]
      },
      {
        "source": "**/*.@(jpg|jpeg|gif|png|svg|webp|js|css|eot|otf|ttf|ttc|woff|font.css)",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache"
          }
        ]
      },
      {
        "source": "ngsw-worker.js",
        "headers": [
          {
            "key": "Cache-Control",
            "value": "no-cache"
          }
        ]
      }
    ]
  }
}

**Comment by strogof** [comment]
Dear Dayana,
I don't know, if you can't, don't want or aren't able to help me.
what i know is that you have been kidding me for two weeks.
let's finish it here
Luigi

**Comment by djabif** [comment]
I think we are not understanding each other.
I have no interest on kidding you.  I was honestly trying to help. 
I can offer you a refund if you are not satisfied with the template and don't plan to use it.
Let's finish this here. 
I will close the issues.

**Comment by strogof** [comment]
I don't think it can be closed.
even though I have given up on your support
the bug reported is always there.
provided that one day you decide to check ...
