### ISSUE TITLE
It seems that this starter is still using UIWebView

### ISSUE THREAD

**Issue by dev-nossos** [ionicthemes/ionic5-starter-app#27]
Hi,

We keep getting this message from Apple Store. 

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Here is the relevant part of our package.json

"dependencies": {
    "@angular/common": "^9.1.4",
    "@angular/core": "^9.1.4",
    "@angular/fire": "6.0.0",
    "@angular/forms": "^9.1.4",
    "@angular/platform-browser": "^9.1.4",
    "@angular/platform-browser-dynamic": "^9.1.4",
    "@angular/router": "^9.1.4",
    "@angular/service-worker": "^9.1.4",
    "@capacitor/android": "^2.1.0",
    "@capacitor/cli": "^2.1.0",
    "@capacitor/core": "^2.1.0",
    "@capacitor/ios": "^2.1.0",
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/social-sharing": "^5.22.0-beta-1",
    "@ionic/angular": "^5.1.0",
    "@ionic/core": "^5.3.3",
    "@ionic/storage": "^2.3.1",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@nicky-lenaers/ngx-scroll-to": "^9.0.0",
    "@pluritech/ion-currencymask": "^1.0.4",
    "angular-pipes": "^10.0.0",
    "br-mask": "0.0.10",
    "capacitor-firebase-auth": "^0.3.1",
    "cordova-plugin-ionic": "5.4.7",
    "cordova-plugin-whitelist": "^1.3.4",
    "core-js": "^2.6.11",
    "dayjs": "^1.8.26",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^7.22.1",
    "google-libphonenumber": "^3.2.9",
    "ionic2-calendar": "^0.6.6",
    "jetifier": "^1.6.5",
    "moment": "^2.29.0",
    "ngx-mask-ionic": "^1.1.2",
    "npm": "^6.14.5",
    "rxjs": "6.5.5",
    "text-mask-core": "^5.1.2",
    "tslib": "^1.11.2",
    "videogular2": "^7.0.2",
    "washyourmouthoutwithsoap": "^1.0.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.901.4",
    "@angular-devkit/build-angular": "~0.901.4",
    "@angular-devkit/core": "^9.1.4",
    "@angular-devkit/schematics": "^9.1.4",
    "@angular/cli": "^9.1.4",
    "@angular/compiler": "^9.1.4",
    "@angular/compiler-cli": "^9.1.4",
    "@angular/language-service": "~9.1.4",
    "@commitlint/cli": "^8.1.0",
    "@commitlint/config-angular": "^8.1.0",
    "@ionic/angular-toolkit": "^2.2.0",
    "@ionic/lab": "3.2.9",
    "@types/core-js": "^2.5.0",
    "@types/googlemaps": "^3.39.2",
    "@types/node": "^12.11.1",
    "@webcomponents/webcomponentsjs": "^2.4.3",
    "codelyzer": "^5.2.2",
    "cordova-sqlite-storage": "^5.1.0",
    "husky": "^4.2.5",
    "node-sass": "^4.14.1",
    "prettier": "^2.1.0",
    "ts-node": "^8.10.1",
    "tslint": "^6.1.2",
    "typescript": "~3.8.3"
  },
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {}
    }
  }
}

We haven't been able to migrate the project to the latest version of the starter. We will do it asap.

**Comment by djabif** [comment]
Hey, please read [this post](https://ionicframework.com/blog/understanding-itms-90809-uiwebview-api-deprecation/) that explains how to solve this issue.
