### ISSUE TITLE
side menu direction is not working properly between rtl and ltr changes 

### ISSUE THREAD

**Issue by alkahtani** [ionicthemes/ionic5-starter-app#28]
I have an issue when changing app language between RTL and LTR ,app default language is RTL and the side menu direction working as expected but when changing the language to LTR the app side menu still slide and hide to RTL from "from right" , it seems the slide animation need to be recalculated  when changing between RTL and LTR 

https://user-images.githubusercontent.com/13502824/108836019-60611a80-75e1-11eb-8de2-6c9213fb43cd.mp4

**Comment by djabif** [comment]
Hi, you can use [ion-side-menu side property](https://ionicframework.com/docs/api/menu#properties) to determine which side of the view the menu should be placed (end or start).

**Comment by djabif** [comment]
Hey @alkahtani, were you able to solve this?
Can I close this issue?
