### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by meduar** [ionicthemes/ionic5-starter-app#29]
Hi,

I just bought the pro theme, I was wondering if is there any module that is suitable to implement **push notifications with firebase.**.

Thanks,

**Comment by djabif** [comment]
Yes, you can follow the steps from [this tutorial](https://ionicthemes.com/tutorials/about/the-complete-guide-to-progressive-web-apps-with-ionic4#adding-push-notifications-to-our-ionic-pwa) to add Push Notifications to an Ionic Angular app using Firebase Cloud Messaging (FCM) as a push server to handle the delivery of notifications across platforms and devices.
