### ISSUE TITLE
theme question new page

### ISSUE THREAD

**Issue by kezman10** [ionicthemes/ionic5-starter-app#30]
I would appreciate a quick response, I am using your theme in the pro version, and I try to create a new page, the year perfectly in the routing file, but whenever I link from the categories page, it tells me page not found, instead if this new page created I use it when the path is `` that is to say empty, if it works for me ... I understand that something happens. Secondly, when I use the login form with navigatebyurl I send it to categories, and if I click on any page that it declares not found, when returning it loses css styles, any help?

**Comment by djabif** [comment]
Hi, I have responded to your email with this question.
Let's keep the communication centered in one place.
Thanks.
