### ISSUE TITLE
How to change dollar symbol for pricing

### ISSUE THREAD

**Issue by magnusmel** [ionicthemes/ionic5-starter-app#7]
How does one change dollar symbol that appears in the fashion menu for product pricing to a different currency ? 
I noticed polyfill.ts has import intl and import intl/local-data .

Did that but, ended up with an error global not defined.

I managed to get it working with  item | currency:'₹'  - filter.
Is there a better way to do with intl directly setting the locale on a global variable ?

**Comment by djabif** [comment]
Hi @magnusmel, we use the Angular [CurrencyPipe](https://angular.io/api/common/CurrencyPipe) which transforms a number to a currency string, formatted according to locale rules. 

You can set your locale info in `src/app/app.module.ts` like this (this example is for french, but you should use your locale currency):
```
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

// the second parameter 'fr' is optional
registerLocaleData(localeFr, 'fr');
```

You can find more information about internationalizing angular pipes in https://angular.io/guide/i18n#i18n-pipes

Also, [here](https://github.com/angular/angular/issues/25461#issuecomment-522009402) there is a workaround that creates a custom pipe that extends the original CurrencyPipe and give your default parameter.

Hope any of these helps!
